# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "f97461246567365c0a20a7d34e5dca4c"
application_url = "https://shopify.dev/apps/default-app-home"
embedded = true
name = "llama-farm-app"
handle = "llama-farm-app"

[webhooks]
api_version = "2025-01"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
# read_orders,write_orders,read_order_edits,write_order_edits
scopes = "write_products,read_customers"

[auth]
redirect_urls = [ "https://shopify.dev/apps/default-app-home/api/auth" ]

[pos]
embedded = false

[build]
dev_store_url = "llama-farm.myshopify.com"
